.TH FEMTO 1
.SH NAME
femto - a cross-platform, command-line text editor.
.SH SYNOPIS
.B femto
.RI [ file ]
.SH DESCRIPTION
.B femto
is a simple, easy-to-use text editor.
.SH EDITING
Entering text and moving around in a file is straightforward: typing the letters and using the normal cursor movement keys. Commands are entered by using the Control (^) key. Typing
.B ^S
will save the current file. A
.B ^Q
will close the editor.
.SH OPTIONS
.B femto
does not take any options.
.SH AUTHOR
Wadim X. Janikowski
